### ISSUE TITLE
Question: which branch of mujoco-py and version of mujoco product you using 

### ISSUE THREAD

**Issue by huangjiancong1** [RussellM2020/GMPS#1]
Hello,@RussellM2020, i have met some error when combining the training env, and want to ask you some questions:
The Mujoco software version: 131? 150? 200? It seems that only 150 can run the multiworld env.

**Comment by huangjiancong1** [comment]
My error:
```
2019-04-25 22:15:17.810805 CST | itr #0 | Obtaining samples for iteration 0...
Found 1 GPUs for rendering. Using device 0.
Traceback (most recent call last):
  File "local_train.py", line 256, in <module>
    experiment(variant)
  File "local_train.py", line 236, in experiment
    algo.train()
  File "/home/jim/gmps/sandbox/rocky/tf/algos/batch_maml_polopt.py", line 396, in train
    logger.dump_tabular(with_prefix=False)
  File "/home/jim/anaconda2/envs/gmps/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1545, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "/home/jim/anaconda2/envs/gmps/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jim/anaconda2/envs/gmps/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5086, in get_controller
    yield g
  File "/home/jim/anaconda2/envs/gmps/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jim/anaconda2/envs/gmps/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 4896, in get_controller
    yield default
  File "/home/jim/anaconda2/envs/gmps/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5086, in get_controller
    yield g
  File "/home/jim/gmps/sandbox/rocky/tf/algos/batch_maml_polopt.py", line 396, in train
    logger.dump_tabular(with_prefix=False)
  File "/home/jim/anaconda2/envs/gmps/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jim/gmps/rllab/misc/logger.py", line 156, in prefix
    yield
  File "/home/jim/gmps/sandbox/rocky/tf/algos/batch_maml_polopt.py", line 328, in train
    log_prefix=str(step),testitr=itr in self.testing_itrs,preupdate=True)
  File "/home/jim/gmps/sandbox/rocky/tf/algos/batch_maml_polopt.py", line 242, in obtain_samples
    paths = self.sampler.obtain_samples(itr=itr, reset_args=reset_args, return_dict=True, log_prefix=log_prefix, extra_input=self.extra_input, extra_input_dim=(self.extra_input_dim if self.extra_input is not None else 0), preupdate=preupdate)
  File "/home/jim/gmps/sandbox/rocky/tf/samplers/vectorized_sampler.py", line 110, in obtain_samples
    obses = self.vec_env.reset(reset_args)
  File "/home/jim/gmps/sandbox/rocky/tf/envs/vec_env_executor.py", line 32, in reset
    results = [env.reset(reset_args=arg) for env, arg in zip(self.envs, reset_args)]
  File "/home/jim/gmps/sandbox/rocky/tf/envs/vec_env_executor.py", line 32, in <listcomp>
    results = [env.reset(reset_args=arg) for env, arg in zip(self.envs, reset_args)]
  File "/home/jim/gmps/rllab/envs/proxy_env.py", line 13, in reset
    return self._wrapped_env.reset(*args, **kwargs)
  File "/home/jim/gmps/multiworld/core/finn_maml_env.py", line 54, in reset
    return self.get_flat_obs()
  File "/home/jim/gmps/multiworld/core/flat_goal_env.py", line 73, in get_flat_obs
    obs = self.wrapped_env._get_obs()
  File "/home/jim/gmps/multiworld/envs/mujoco/sawyer_xyz/push/sawyer_push.py", line 142, in _get_obs
    image = self.render(mode = 'nn')
  File "/home/jim/gmps/multiworld/envs/mujoco/sawyer_xyz/push/sawyer_push.py", line 167, in render
    image = self.get_image(width= im_size , height = im_size , camera_name = 'robotview_zoomed').transpose()/norm
  File "/home/jim/gmps/multiworld/envs/mujoco/mujoco_env.py", line 150, in get_image
    camera_name=camera_name,
  File "mjsim.pyx", line 149, in mujoco_py.cymj.MjSim.render
  File "mjsim.pyx", line 151, in mujoco_py.cymj.MjSim.render
  File "mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mjrendercontext.pyx", line 108, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "opengl_context.pyx", line 128, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL

```
